export const ADD_ELEMENTS = '@@APP/ROOT/ADD__ELEMENTS';
export const DELETE_ELEMENT = '@@APP/ROOT/DELETE__ELEMENT';
export const ADD_TO_FAVORITES = '@@APP/ROOT/ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = '@@APP/ROOT/REMOVE_FROM_FAVORITES';
